WIP docker init
clio/example-third-party-application pull request #5
Opened 2022-07-11 23:09 UTC by deanna-cooney

2022-07-12 16:21 UTC, arian-kh commented on docker-compose.yml
> +#   failed to connect: Connection refused - connect(2) for "account.myclio.ca" port 1337
This means Switchboard is unable to resolve `account.myclio.ca`, similar to how Docusign was unable to resolve `app.myclio.ca`. The same fix could help here.

2022-07-12 21:09 UTC, JohnPark97 approved these changes
LGTM 😁 
![giphub](https://media0.giphy.com/media/9E40ePI5P22Wngf4mA/giphy.gif)

2022-07-13 14:47 UTC, stevelyall requested changes
QA passes when the environment variables are set in the `local_env.yaml` 👍 

- [ ] `.env` not loading in a fresh setup? 

Made some small suggestions to the readmes, but otherwise looks good! 

Nice work!
<img src="https://media1.giphy.com/media/lqdJsUDvJnHBgM82HB/giphy-downsized-medium.gif"/>

2022-07-13 14:47 UTC, stevelyall commented on docs/manual_setup.md
> +host: db
```suggestion
host: sb_db
```

Nitpick- this seems to be the current value of host in `database` I had to remove for manual config

2022-07-13 14:47 UTC, stevelyall commented on docs/docker_setup.md
> +## Manual Setup
```suggestion
## Docker Setup
```

2022-07-13 14:47 UTC, stevelyall commented on README.md
> +Then update the environment variables in `.env`:
I had to change `local_env.yml` for the app to load the environment variables properly. It doesn't seem to be loading from the `.env` instead.  I may have missed a step?

Are you intending to use `dotenv-rails` and `Dotenv.load` in the config?

2022-07-13 14:55 UTC, deanna-cooney commented on README.md
> +Then update the environment variables in `.env`:
There is no `.env`, just missed updating this line in the readme.

2022-07-13 14:57 UTC, stevelyall approved these changes
QA Pass

2022-07-13 14:59 UTC, merged